"""add SM inventory lifecycle columns

Revision ID: 90b349ba1c61
Revises: d854c4dacf49
Create Date: 2026-03-29 21:26:35.968048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b349ba1c61'
down_revision: Union[str, Sequence[str], None] = 'd854c4dacf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_batch', sa.Column('wip_output_expected_m', sa.Numeric(), nullable=True))
    op.add_column('production_batch', sa.Column('wip_output_actual_m', sa.Numeric(), nullable=True))
    op.add_column('wip_inventory', sa.Column('expected_length_m', sa.Numeric(), nullable=True))
    op.add_column('wip_inventory', sa.Column('actual_length_m', sa.Numeric(), nullable=True))
    op.add_column('wip_inventory', sa.Column('variance_m', sa.Numeric(), nullable=True))
    op.add_column('wip_inventory', sa.Column('source_batch_id', sa.Integer(), nullable=True))
    op.add_column('wip_inventory', sa.Column('matched_order_id', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'wip_inventory', 'production_batch', ['source_batch_id'], ['batch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wip_inventory', type_='foreignkey')
    op.drop_column('wip_inventory', 'matched_order_id')
    op.drop_column('wip_inventory', 'source_batch_id')
    op.drop_column('wip_inventory', 'variance_m')
    op.drop_column('wip_inventory', 'actual_length_m')
    op.drop_column('wip_inventory', 'expected_length_m')
    op.drop_column('production_batch', 'wip_output_actual_m')
    op.drop_column('production_batch', 'wip_output_expected_m')
    # ### end Alembic commands ###
