"""initial schema — 14 tables

Revision ID: d854c4dacf49
Revises: 
Create Date: 2026-03-29 19:16:20.955319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd854c4dacf49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_config',
    sa.Column('constraint_id', sa.String(length=10), nullable=False),
    sa.Column('constraint_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_processes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('implementation_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_table('customer_master',
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_type', sa.String(length=20), nullable=True),
    sa.Column('due_strictness', sa.String(length=50), nullable=True),
    sa.Column('require_sample', sa.Boolean(), nullable=True),
    sa.Column('urgency_frequency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('customer_code')
    )
    op.create_table('decision_criteria',
    sa.Column('criteria_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria_name', sa.String(length=100), nullable=False),
    sa.Column('criteria_value', sa.String(length=50), nullable=False),
    sa.Column('criteria_unit', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('criteria_id')
    )
    op.create_table('drum_lot_master',
    sa.Column('drum_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cross_section', sa.Numeric(), nullable=False),
    sa.Column('wire_diameter', sa.Numeric(), nullable=True),
    sa.Column('wire_count', sa.Integer(), nullable=True),
    sa.Column('lot_wire_drawing', sa.Numeric(), nullable=True),
    sa.Column('lot_stranding', sa.Numeric(), nullable=True),
    sa.Column('daily_production', sa.Numeric(), nullable=True),
    sa.Column('setup_time_min', sa.Numeric(), nullable=True),
    sa.Column('drum_weight_ton', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('drum_id')
    )
    op.create_table('equipment_master',
    sa.Column('equipment_code', sa.String(length=20), nullable=False),
    sa.Column('equipment_name', sa.String(length=50), nullable=False),
    sa.Column('process_name', sa.String(length=30), nullable=False),
    sa.Column('material_limit', sa.String(length=10), nullable=True),
    sa.Column('range_min', sa.Numeric(), nullable=True),
    sa.Column('range_max', sa.Numeric(), nullable=True),
    sa.Column('range_unit', sa.String(length=10), nullable=True),
    sa.Column('stranding_method', sa.String(length=50), nullable=True),
    sa.Column('color_group', sa.String(length=50), nullable=True),
    sa.Column('base_working_hours', sa.Numeric(), nullable=True),
    sa.Column('shift_type', sa.String(length=20), nullable=True),
    sa.Column('calendar_rule_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('equipment_code')
    )
    op.create_table('operation_calendar',
    sa.Column('calendar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('working_hours', sa.Numeric(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('deduction_hours', sa.Numeric(), nullable=True),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_index(op.f('ix_operation_calendar_rule_code'), 'operation_calendar', ['rule_code'], unique=False)
    op.create_table('process_routing',
    sa.Column('routing_code', sa.String(length=20), nullable=False),
    sa.Column('routing_name', sa.String(length=100), nullable=False),
    sa.Column('process_1', sa.String(length=30), nullable=True),
    sa.Column('process_2', sa.String(length=30), nullable=True),
    sa.Column('process_3', sa.String(length=30), nullable=True),
    sa.Column('process_4', sa.String(length=30), nullable=True),
    sa.Column('process_5', sa.String(length=30), nullable=True),
    sa.Column('process_6', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('routing_code')
    )
    op.create_table('wip_inventory',
    sa.Column('wip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_stage', sa.String(length=30), nullable=True),
    sa.Column('voltage_class', sa.String(length=20), nullable=True),
    sa.Column('material', sa.String(length=10), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.String(length=100), nullable=True),
    sa.Column('cross_section', sa.Numeric(), nullable=True),
    sa.Column('length_m', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('total_length_m', sa.Numeric(), nullable=True),
    sa.Column('core_colors', sa.String(length=100), nullable=True),
    sa.Column('wire_diameter', sa.Numeric(), nullable=True),
    sa.Column('wire_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('run_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('wip_id')
    )
    op.create_table('item_master',
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('spec_abbr', sa.String(length=100), nullable=True),
    sa.Column('product_group', sa.String(length=50), nullable=True),
    sa.Column('voltage', sa.String(length=20), nullable=True),
    sa.Column('conductor_material', sa.String(length=10), nullable=True),
    sa.Column('wire_diameter', sa.Numeric(), nullable=True),
    sa.Column('wire_count', sa.Integer(), nullable=True),
    sa.Column('cross_section', sa.Numeric(), nullable=True),
    sa.Column('core_count', sa.Integer(), nullable=True),
    sa.Column('stranding_type', sa.String(length=20), nullable=True),
    sa.Column('insulation_type', sa.String(length=50), nullable=True),
    sa.Column('sheath_type', sa.String(length=50), nullable=True),
    sa.Column('core_colors', sa.String(length=100), nullable=True),
    sa.Column('routing_code', sa.String(length=20), nullable=True),
    sa.Column('drum_max_length', sa.Numeric(), nullable=True),
    sa.Column('lot_length', sa.Numeric(), nullable=True),
    sa.Column('extra_allowance', sa.Numeric(), nullable=True),
    sa.Column('daily_production', sa.Numeric(), nullable=True),
    sa.Column('unit_weight', sa.Numeric(), nullable=True),
    sa.Column('require_sample', sa.Boolean(), nullable=True),
    sa.Column('is_outsourced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['routing_code'], ['process_routing.routing_code'], ),
    sa.PrimaryKeyConstraint('item_code')
    )
    op.create_table('speed_master',
    sa.Column('speed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_code', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('cross_section', sa.Numeric(), nullable=True),
    sa.Column('line_speed_mpm', sa.Numeric(), nullable=True),
    sa.Column('line_speed_hr', sa.Numeric(), nullable=True),
    sa.Column('setup_start_min', sa.Numeric(), nullable=True),
    sa.Column('setup_spec_min', sa.Numeric(), nullable=True),
    sa.Column('setup_color_min', sa.Numeric(), nullable=True),
    sa.Column('setup_compound_min', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_code'], ['equipment_master.equipment_code'], ),
    sa.PrimaryKeyConstraint('speed_id')
    )
    op.create_table('production_batch',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_label', sa.String(length=50), nullable=False),
    sa.Column('sales_order_id', sa.String(length=30), nullable=True),
    sa.Column('sales_order_line', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('routing_code', sa.String(length=20), nullable=True),
    sa.Column('process_name', sa.String(length=30), nullable=False),
    sa.Column('equipment_code', sa.String(length=20), nullable=True),
    sa.Column('batch_seq', sa.Integer(), nullable=True),
    sa.Column('drum_length_m', sa.Numeric(), nullable=True),
    sa.Column('drum_count', sa.Integer(), nullable=True),
    sa.Column('total_length_m', sa.Numeric(), nullable=True),
    sa.Column('extra_length_m', sa.Numeric(), nullable=True),
    sa.Column('sq_mm2', sa.Numeric(), nullable=True),
    sa.Column('core_count', sa.Integer(), nullable=True),
    sa.Column('core_colors', sa.String(length=100), nullable=True),
    sa.Column('sheath_color', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('customer_priority', sa.Integer(), nullable=True),
    sa.Column('wip_matched_id', sa.Integer(), nullable=True),
    sa.Column('line_speed_mpm', sa.Numeric(), nullable=True),
    sa.Column('setup_time_min', sa.Numeric(), nullable=True),
    sa.Column('estimated_duration_min', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('product_group', sa.String(length=50), nullable=True),
    sa.Column('voltage', sa.String(length=20), nullable=True),
    sa.Column('conductor_material', sa.String(length=10), nullable=True),
    sa.Column('stranding_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_code'], ['equipment_master.equipment_code'], ),
    sa.ForeignKeyConstraint(['item_code'], ['item_master.item_code'], ),
    sa.ForeignKeyConstraint(['routing_code'], ['process_routing.routing_code'], ),
    sa.ForeignKeyConstraint(['wip_matched_id'], ['wip_inventory.wip_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_production_batch_run_label'), 'production_batch', ['run_label'], unique=False)
    op.create_table('sales_order',
    sa.Column('order_id', sa.String(length=30), nullable=False),
    sa.Column('order_line', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('product_group', sa.String(length=50), nullable=True),
    sa.Column('voltage', sa.String(length=20), nullable=True),
    sa.Column('spec_raw', sa.String(length=100), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_type', sa.String(length=20), nullable=True),
    sa.Column('customer_priority', sa.Integer(), nullable=True),
    sa.Column('drum_length_m', sa.Numeric(), nullable=True),
    sa.Column('drum_count', sa.Integer(), nullable=True),
    sa.Column('ordered_qty_m', sa.Numeric(), nullable=True),
    sa.Column('self_plan_qty_m', sa.Numeric(), nullable=True),
    sa.Column('outsource_qty_m', sa.Numeric(), nullable=True),
    sa.Column('unit_price_krw', sa.Numeric(), nullable=True),
    sa.Column('amount_krw', sa.Numeric(), nullable=True),
    sa.Column('cu_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('al_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('core_count', sa.Integer(), nullable=True),
    sa.Column('core_colors', sa.String(length=100), nullable=True),
    sa.Column('sheath_color', sa.String(length=50), nullable=True),
    sa.Column('neutral_wire', sa.String(length=50), nullable=True),
    sa.Column('use_wip', sa.Boolean(), nullable=True),
    sa.Column('wip_type', sa.String(length=20), nullable=True),
    sa.Column('actual_length_m', sa.Numeric(), nullable=True),
    sa.Column('is_outsourced', sa.Boolean(), nullable=True),
    sa.Column('run_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customer_master.customer_code'], ),
    sa.ForeignKeyConstraint(['item_code'], ['item_master.item_code'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_line')
    )
    op.create_table('schedule_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('equipment_code', sa.String(length=20), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('predecessor_task_id', sa.Integer(), nullable=True),
    sa.Column('setup_time_min', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('run_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['equipment_code'], ['equipment_master.equipment_code'], ),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['schedule_task.task_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_schedule_task_run_label'), 'schedule_task', ['run_label'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_label', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('constraints_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['schedule_task.task_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_log_run_label'), 'audit_log', ['run_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_run_label'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_schedule_task_run_label'), table_name='schedule_task')
    op.drop_table('schedule_task')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_production_batch_run_label'), table_name='production_batch')
    op.drop_table('production_batch')
    op.drop_table('speed_master')
    op.drop_table('item_master')
    op.drop_table('wip_inventory')
    op.drop_table('process_routing')
    op.drop_index(op.f('ix_operation_calendar_rule_code'), table_name='operation_calendar')
    op.drop_table('operation_calendar')
    op.drop_table('equipment_master')
    op.drop_table('drum_lot_master')
    op.drop_table('decision_criteria')
    op.drop_table('customer_master')
    op.drop_table('constraint_config')
    # ### end Alembic commands ###
